@startuml
start
:User executes addModLinkCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([all prefixes present])
    :Parse prefixes;
    if () then ([all prefixes
    formatted correctly])
        :Find corresponding
        module in Model;
        if () then ([module is found])
            :Add Pair of ModLink and
            String to module;
            :Replace module in Model
            with edited module;
        else ([else])
            :Display error message that
            module cannot be found;
        endif
    else ([else])
        :Display error message on
        invalid prefix format;
    endif
else ([else])
    :Display error message
    and show command format;
endif
stop
@enduml
