@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TAbleParser" as TAbleParser LOGIC_COLOR
participant ":FindReminderCommandParser" as FindReminderCommandParser LOGIC_COLOR
participant "f:FindReminderCommand" as FindReminderCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("findReminder \ndesc/midterms date/2020-03-05")
activate LogicManager

LogicManager -> TAbleParser : parseCommand("findReminder \ndesc/midterms date/2020-03-05")
activate TAbleParser

create FindReminderCommandParser
TAbleParser -> FindReminderCommandParser
activate FindReminderCommandParser

FindReminderCommandParser --> TAbleParser
deactivate FindReminderCommandParser

TAbleParser -> FindReminderCommandParser : parse("midterms", "2020-03-05")
activate FindReminderCommandParser

create FindReminderCommand
FindReminderCommandParser -> FindReminderCommand
activate FindReminderCommand

FindReminderCommand --> FindReminderCommandParser : f
deactivate FindReminderCommand

FindReminderCommandParser --> TAbleParser : f
deactivate FindReminderCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindReminderCommandParser -[hidden]-> TAbleParser
destroy FindReminderCommandParser

TAbleParser --> LogicManager : f
deactivate TAbleParser

LogicManager -> FindReminderCommand : execute()
activate FindReminderCommand

FindReminderCommand -> Model : updateFilteredReminderList(2020-03-05, midterms)
activate Model

Model --> FindReminderCommand
deactivate Model

create CommandResult
FindReminderCommand -> CommandResult
activate CommandResult

CommandResult --> FindReminderCommand
deactivate CommandResult

FindReminderCommand --> LogicManager : result
deactivate FindReminderCommand

[<--LogicManager
deactivate LogicManager
@enduml
