@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Student {
Interface ReadOnlyStudentTAble <<Interface>>
Class ReadOnlyStudentTAble
Class Student
Class Email
Class Name
Class MatricNumber
Class UniqueStudentList
Class StudentTAble
}

Package Mod {
Class ModTAble
}

Package Reminder {
Class ReminderTAble
}

Package Event {

Package Tutorial {
Class TutorialTAble
}

Package Consult {
Class ConsultTAble
}
}


Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

StudentTAble .up.|> ReadOnlyStudentTAble

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" StudentTAble
ModelManager o--> "1" ModTAble
ModelManager o--> "1" ConsultTAble
ModelManager o--> "1" TutorialTAble
ModelManager o--> "1" ReminderTAble
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

StudentTAble *--> "1" UniqueStudentList
UniqueStudentList o--> "*" Student
Student *--> Name
Student *--> MatricNumber
Student *--> Email
Student *--> "*" Tag

Tag -[hidden]right-> Name
Name -[hidden]right-> MatricNumber
MatricNumber -[hidden]right-> Email

ModelManager -->"1" Student : filtered list

ModTAble .[hidden]down.> ReminderTAble
ReminderTAble .[hidden]left.> TutorialTAble
ConsultTAble -[hidden]right-> StudentTAble
@enduml
