@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface AddressBookStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonAddressBookStorage

Package Consults {
Interface ConsultStorage <<Interface>>
Class JsonAdaptedConsult
Class JsonConsultStorage
Class JsonSerializableConsults
}

Package Mods {
Interface ModStorage <<Interface>>
}

Package Reminders {
Interface ReminderStorage <<Interface>>
}

Package Tutorials {
Interface TutorialStorage <<Interface>>
}

StorageManager .up.|> Storage
StorageManager o-up-> UserPrefsStorage
StorageManager o-right-> AddressBookStorage
StorageManager o--> ConsultStorage
StorageManager o--> ModStorage
StorageManager o--> ReminderStorage
StorageManager o--> TutorialStorage

JsonUserPrefsStorage ..|> UserPrefsStorage

JsonAddressBookStorage ..|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBookStorage
JsonSerializableAddressBookStorage ..> JsonAdaptedStudent
JsonAdaptedStudent ..> JsonAdaptedTag

JsonConsultStorage ..|> ConsultStorage
JsonConsultStorage ..> JsonSerializableConsults
JsonSerializableConsults ..> JsonAdaptedConsult

@enduml
