@startuml
start
:User executes markPresent command;

if () then ([given week is valid])
:Find student in specified tutorial;

if () then ([student exists in the tutorial])
    :Update studentAttendance for specified student
    and given week to present;
    :Save updated tutorial in TutorialTAble;
else ([else])
    :Throw exception;
endif
else ([else])
    :Throw exception;
endif

stop
@enduml
