@startuml
start
:User executes markPresent command;

if () then ([all prefixes present and no
multiple of the same prefix])
    if () then ([given week is valid])
        if () then ([tutorial exists in TAble])
            :Find student in the specified tutorial;

            if () then ([student exists in the tutorial])
                :Update studentAttendance for specified student
                and given week to present;
                :Save updated tutorial in TutorialTAble;
            else ([else])
                :Display error message that
                student index provided is invalid;
            endif
        else ([else])
            :Display error message that
            tutorial cannot be found;
        endif
    else ([else])
        :Display error message on
        invalid prefix format, telling user
        to input a week between 3-13 (inclusive);
    endif
else ([else])
   :Display error message
   and show command format;
endif

stop
@enduml
